[[rustfft]]
arch = "aarch64"
git-tree-sha1 = "e88662aab0d8f2742dbde487f2833af2dd5effae"
julia_version = "1.7.0"
os = "macos"

    [[rustfft.download]]
    sha256 = "99bd5083ce21338705d919a384f9b3689b29e6201559030d4b1bde0a0754ef1c"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.3.0+0/rustfft.v0.3.0.aarch64-apple-darwin-julia_version+1.7.0.tar.gz"
[[rustfft]]
arch = "aarch64"
git-tree-sha1 = "a54a8dc192f0b911ed09ec6df28e9d898382e34e"
julia_version = "1.8.0"
os = "macos"

    [[rustfft.download]]
    sha256 = "f042d225d9438c34bd28265b94ffee4191d4f0b4b84c24f85065259213f04eb5"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.3.0+0/rustfft.v0.3.0.aarch64-apple-darwin-julia_version+1.8.0.tar.gz"
[[rustfft]]
arch = "aarch64"
git-tree-sha1 = "9e42a33b99eeb2c54fb6f685c291ea3bf0df4ccf"
julia_version = "1.9.0"
os = "macos"

    [[rustfft.download]]
    sha256 = "b9b939444c7a3fda098bb94c510ce0cb725cc07aa516559f4b05f2a7089a0416"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.3.0+0/rustfft.v0.3.0.aarch64-apple-darwin-julia_version+1.9.0.tar.gz"
[[rustfft]]
arch = "aarch64"
git-tree-sha1 = "662a3531ccdf70783d15fc6b374b7d217dab01ec"
julia_version = "1.6.3"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "7a7a8733a3d35d7db6c87ed131c9099cf7743b11d714a64444b29156a467c88e"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.3.0+0/rustfft.v0.3.0.aarch64-linux-gnu-julia_version+1.6.3.tar.gz"
[[rustfft]]
arch = "aarch64"
git-tree-sha1 = "d9daf42fd4124e198f4b3d222f6fed7d0663186d"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "2efb13ecb42e5527ab8b2320c958464542d66f444ceabd45d760e0a86ba97344"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.3.0+0/rustfft.v0.3.0.aarch64-linux-gnu-julia_version+1.7.0.tar.gz"
[[rustfft]]
arch = "aarch64"
git-tree-sha1 = "f2bb01dee92826567a3b174c9cad22711a92386c"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "36d02c230c88c3dcb348695e1696b783e9b6fd390627920ec632b762b3a52d1d"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.3.0+0/rustfft.v0.3.0.aarch64-linux-gnu-julia_version+1.8.0.tar.gz"
[[rustfft]]
arch = "aarch64"
git-tree-sha1 = "35f6ddaf538b6394f979437613da88ad34b1c1ba"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "455ac5ad79f932a95538e2618105801a58ed4845f80fd72ed656e1acbaad87b4"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.3.0+0/rustfft.v0.3.0.aarch64-linux-gnu-julia_version+1.9.0.tar.gz"
[[rustfft]]
arch = "aarch64"
git-tree-sha1 = "95be012ce227f1b144c9f052e6e4779aa8f329bf"
julia_version = "1.6.3"
libc = "musl"
os = "linux"

    [[rustfft.download]]
    sha256 = "42462417145a935cf288ad5eff3a86d1a67bddb8af80909f1deeeeaced70c39f"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.3.0+0/rustfft.v0.3.0.aarch64-linux-musl-julia_version+1.6.3.tar.gz"
[[rustfft]]
arch = "aarch64"
git-tree-sha1 = "275a1f36231e55474172326bbecdf4c569972ea5"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[rustfft.download]]
    sha256 = "acdf2c676c1799e5afaf396bef102b7942c68c05377f0f04146c7157dd058666"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.3.0+0/rustfft.v0.3.0.aarch64-linux-musl-julia_version+1.7.0.tar.gz"
[[rustfft]]
arch = "aarch64"
git-tree-sha1 = "43ac9cd8181d127f224b02ee09cf6664b755f7a5"
julia_version = "1.8.0"
libc = "musl"
os = "linux"

    [[rustfft.download]]
    sha256 = "49813cb46b79be8e7b5cf1583e753313805a981b615391626c4d429dfe2dcc95"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.3.0+0/rustfft.v0.3.0.aarch64-linux-musl-julia_version+1.8.0.tar.gz"
[[rustfft]]
arch = "aarch64"
git-tree-sha1 = "16144ceaeee39f533587addace689d59a4e6fa99"
julia_version = "1.9.0"
libc = "musl"
os = "linux"

    [[rustfft.download]]
    sha256 = "10b258c0195427c6594af6072712918d5183d55e7be3fe51da40def9928e61f9"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.3.0+0/rustfft.v0.3.0.aarch64-linux-musl-julia_version+1.9.0.tar.gz"
[[rustfft]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f45cb6e88b314e66d5b865449a5f2f799f452944"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "47c71a4f613bb6e5a845481cc87950ca8dcb92576367ea4f7038cd97653f1f7c"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.3.0+0/rustfft.v0.3.0.armv6l-linux-gnueabihf-julia_version+1.7.0.tar.gz"
[[rustfft]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6218708fc6707cb3eca12494259acff80d9ea019"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "7e4c7b98bc4f96f58fe625ad145c0d18bbacf109a6dcbf6d66d2f129c9602fb8"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.3.0+0/rustfft.v0.3.0.armv6l-linux-gnueabihf-julia_version+1.8.0.tar.gz"
[[rustfft]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e4e00d9b16e3d001565695b5778dfd11d2e39695"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[rustfft.download]]
    sha256 = "23c71fc764f6c909000538d0be7fb471c4540d8a6279f559e985928f24396d3b"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.3.0+0/rustfft.v0.3.0.armv6l-linux-musleabihf-julia_version+1.7.0.tar.gz"
[[rustfft]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d8733efbfef5d9d2e1a1c78a8a81c8889ec055ab"
julia_version = "1.8.0"
libc = "musl"
os = "linux"

    [[rustfft.download]]
    sha256 = "30b0da718912332cdb49998108322f5222b272be1ab361c69aece62c8a81b3bf"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.3.0+0/rustfft.v0.3.0.armv6l-linux-musleabihf-julia_version+1.8.0.tar.gz"
[[rustfft]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a8f856d6ac77c47c94ebe6ba38c9985360950438"
julia_version = "1.6.3"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "5a3774c00ef0c6c2de2a2237663e0515e0d51933f5254a0c15759fdbf6f7812c"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.3.0+0/rustfft.v0.3.0.armv7l-linux-gnueabihf-julia_version+1.6.3.tar.gz"
[[rustfft]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "70eeb5d08606d818992f0b8c174807671180e1a7"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "663a74f9b1cf55f845a1a2c5eb8eb1e2b8d8d37089862f0f33bfdd5a43359b51"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.3.0+0/rustfft.v0.3.0.armv7l-linux-gnueabihf-julia_version+1.7.0.tar.gz"
[[rustfft]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a8286c099fd33c3acda9257de44361358a8a37cd"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "bb2564b9b52f0ca50e4392d9617432682cca112151d221bf4cbbe94aac78fc79"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.3.0+0/rustfft.v0.3.0.armv7l-linux-gnueabihf-julia_version+1.8.0.tar.gz"
[[rustfft]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "879161ee24a126cc9845c4c15caf899e6652a702"
julia_version = "1.6.3"
libc = "musl"
os = "linux"

    [[rustfft.download]]
    sha256 = "67e089944ca64379bf263ec873906449ef0b6c872d3b99ddacbf5268a55b3e6e"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.3.0+0/rustfft.v0.3.0.armv7l-linux-musleabihf-julia_version+1.6.3.tar.gz"
[[rustfft]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a503736fc69a00750de16c68b961e2f83a73143e"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[rustfft.download]]
    sha256 = "8e5df47f0a63a4fdbfbc0c7cc8d3484ef97ad345fd70f005e860507ff935579b"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.3.0+0/rustfft.v0.3.0.armv7l-linux-musleabihf-julia_version+1.7.0.tar.gz"
[[rustfft]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5468760d6c129dc8557481c8089f59ddfde41753"
julia_version = "1.8.0"
libc = "musl"
os = "linux"

    [[rustfft.download]]
    sha256 = "915ba405e19b64ac7f28a4f1fc0620149738059874047ed6415c66eed060dc29"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.3.0+0/rustfft.v0.3.0.armv7l-linux-musleabihf-julia_version+1.8.0.tar.gz"
[[rustfft]]
arch = "i686"
git-tree-sha1 = "866baedc146cfd7a35e4b4721b9aa18d30b557bb"
julia_version = "1.6.3"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "8c5553515b005bffa7f5c2010b68dc1f9fd303fad36fe6804edb26b941ef1951"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.3.0+0/rustfft.v0.3.0.i686-linux-gnu-julia_version+1.6.3.tar.gz"
[[rustfft]]
arch = "i686"
git-tree-sha1 = "6a469d3c3eec886f92fd578899e3b3d04090c7fd"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "3b0576896b25392becb413057c4ae30d056399b6894fa3f3be32d77947c0a777"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.3.0+0/rustfft.v0.3.0.i686-linux-gnu-julia_version+1.7.0.tar.gz"
[[rustfft]]
arch = "i686"
git-tree-sha1 = "ca9e8e3e03a5995e5c0eab035e17a4ccaff97aa4"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "cd2f33de890573db0f999a0b1a83299d81fd72e7ad715174ae4cf45c51da67e1"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.3.0+0/rustfft.v0.3.0.i686-linux-gnu-julia_version+1.8.0.tar.gz"
[[rustfft]]
arch = "i686"
git-tree-sha1 = "173df80126d3e516901021fbb30ccf96f02c82ff"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "0f297db963ef5a3fb387146c25924aeab5307659e87b00d18133c23f01857178"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.3.0+0/rustfft.v0.3.0.i686-linux-gnu-julia_version+1.9.0.tar.gz"
[[rustfft]]
arch = "powerpc64le"
git-tree-sha1 = "4e3fad9f92a96e8d12ca5b89a2243450c80d2bdd"
julia_version = "1.6.3"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "08362bf60c551e9a15ad06908b1b6e786dd9030b87caa55e4139008492937352"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.3.0+0/rustfft.v0.3.0.powerpc64le-linux-gnu-julia_version+1.6.3.tar.gz"
[[rustfft]]
arch = "powerpc64le"
git-tree-sha1 = "6c7d2ee8b201fb3bd8d4652fe21e86f581beec0e"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "8fb0953624a63ce27b4b16286495761af23f0a4b46297517dfd067ce436a69d1"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.3.0+0/rustfft.v0.3.0.powerpc64le-linux-gnu-julia_version+1.7.0.tar.gz"
[[rustfft]]
arch = "powerpc64le"
git-tree-sha1 = "f6eeb6d0334774c499a2d0a8644ee53c289afc98"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "af0d430c7194eaee15f3e61a31aeea63131debcb9bf1b2391c44baf5cb7f158b"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.3.0+0/rustfft.v0.3.0.powerpc64le-linux-gnu-julia_version+1.8.0.tar.gz"
[[rustfft]]
arch = "powerpc64le"
git-tree-sha1 = "705590b19fc8cd9d3d4931dbaf3a337bc790bde2"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "3b893a9891a43392b268d35d40b1291dcf16f3b3f68a070db45303b697792b9f"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.3.0+0/rustfft.v0.3.0.powerpc64le-linux-gnu-julia_version+1.9.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "f2924ecdbd494ba4589fbc9239df81f7df5acc44"
julia_version = "1.6.3"
os = "macos"

    [[rustfft.download]]
    sha256 = "80d62321d01659c7056e1068c4ce4e18b2c23574a80b083a7b8e801a2a9b241b"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.3.0+0/rustfft.v0.3.0.x86_64-apple-darwin-julia_version+1.6.3.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "197032e516a0ede140b33fc444ba3c6e91444079"
julia_version = "1.7.0"
os = "macos"

    [[rustfft.download]]
    sha256 = "f31505ebc708fc865ff82c43e45af30263a6b4098a698dea25d5cd7bd4caeea7"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.3.0+0/rustfft.v0.3.0.x86_64-apple-darwin-julia_version+1.7.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "a9d560e17fb15da922a7004448c003ec3e739994"
julia_version = "1.8.0"
os = "macos"

    [[rustfft.download]]
    sha256 = "1e0e0eca93fa0f115becdacc71c4e0c798acc0c98c6e95f3939ccfabbd356830"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.3.0+0/rustfft.v0.3.0.x86_64-apple-darwin-julia_version+1.8.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "b3d8eace59df65b9f3158729d0d24ce4514b3959"
julia_version = "1.9.0"
os = "macos"

    [[rustfft.download]]
    sha256 = "bc50043da1850bb86b280aebbfc31875027e9b01708f59d23ae953017c8653a0"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.3.0+0/rustfft.v0.3.0.x86_64-apple-darwin-julia_version+1.9.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "858b95feb9f60c697bd835d3d332497ed05702a0"
julia_version = "1.6.3"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "c2eda3eaa15d5fe3ad3eaeca6c47e294e0f913da72c073be52ef37636800ece3"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.3.0+0/rustfft.v0.3.0.x86_64-linux-gnu-julia_version+1.6.3.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "5b865e7e97faf27cbc159c8b99bb9aa7595a4c22"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "b2420163ae9d883b2b954142cf082917c0b5c83dfa9e4b821dda9d7925590cff"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.3.0+0/rustfft.v0.3.0.x86_64-linux-gnu-julia_version+1.7.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "7d531d22af5ca64c5d9e8815e9c8069ab0989d3a"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "755f91485311a466a4ef82a0b7843a61af133fcf07cbc78514cf31fd0b98e43c"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.3.0+0/rustfft.v0.3.0.x86_64-linux-gnu-julia_version+1.8.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "cd7c9c459b424b2ded1b506687ad2d878d44fbbb"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "50107d1c33a6c11a82852388581b62b47bc78a9a9e03ee9758c5ec7dca498421"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.3.0+0/rustfft.v0.3.0.x86_64-linux-gnu-julia_version+1.9.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "c5ec06ea962580ac618bb9ac18a878db95616418"
julia_version = "1.6.3"
libc = "musl"
os = "linux"

    [[rustfft.download]]
    sha256 = "d675aaee53f7b9ac5a020db274f07df41ec227593a1b311582caad71f574530d"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.3.0+0/rustfft.v0.3.0.x86_64-linux-musl-julia_version+1.6.3.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "83a1eac6b0cb60d808e8d3a2582c359eb23be1d0"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[rustfft.download]]
    sha256 = "8a1e513bd5c98f813fd879bbd8da6995f5c913c57f2ccaadbb5715b25f771b08"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.3.0+0/rustfft.v0.3.0.x86_64-linux-musl-julia_version+1.7.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "ceac86c848c0db2de0674451d6518920ef5fc04f"
julia_version = "1.8.0"
libc = "musl"
os = "linux"

    [[rustfft.download]]
    sha256 = "d535345af94fb094e48fac0e7b0a7537f3ed712e205333ddc966bdbbae903ecc"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.3.0+0/rustfft.v0.3.0.x86_64-linux-musl-julia_version+1.8.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "cf040bb5b989315ff03793a729ae33fc3d73ba27"
julia_version = "1.9.0"
libc = "musl"
os = "linux"

    [[rustfft.download]]
    sha256 = "917becc393fb1e785781e50a45615ed0951db604692380cd44555f714664603f"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.3.0+0/rustfft.v0.3.0.x86_64-linux-musl-julia_version+1.9.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "3b06eb82659f25927524e438bec0940a06a064e3"
julia_version = "1.6.3"
os = "freebsd"

    [[rustfft.download]]
    sha256 = "ae757202f88ff32be2153784d69f4657b397a09d9590fd52f8a14a9232344c43"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.3.0+0/rustfft.v0.3.0.x86_64-unknown-freebsd-julia_version+1.6.3.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "16d26fbda3a45b92f71f963a7f95ea27e6633851"
julia_version = "1.7.0"
os = "freebsd"

    [[rustfft.download]]
    sha256 = "c0e28d86f8c14f175643412ef53dfa1b4d1937c4fbc969d7afe782bcf17d718e"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.3.0+0/rustfft.v0.3.0.x86_64-unknown-freebsd-julia_version+1.7.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "33795545d54c84feefc94eaa2077e94751675696"
julia_version = "1.8.0"
os = "freebsd"

    [[rustfft.download]]
    sha256 = "b54a81606091ba17c338b82cea7101773062fd3792f38d902366a54755bd248d"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.3.0+0/rustfft.v0.3.0.x86_64-unknown-freebsd-julia_version+1.8.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "9c64c4059f257326a59d7e68e34fcd44622bbec2"
julia_version = "1.9.0"
os = "freebsd"

    [[rustfft.download]]
    sha256 = "9f9efc2e9ffe49008b026e1c10ebc84ae3911f6f43b5b741a39eac143562796c"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.3.0+0/rustfft.v0.3.0.x86_64-unknown-freebsd-julia_version+1.9.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "76d7fe2c9eaa7a9fe349242614b66e4471123a30"
julia_version = "1.6.3"
os = "windows"

    [[rustfft.download]]
    sha256 = "70c24f7cdca6893778bacad05bd48d5eb78c76d283ed5ea3ba4f4eaf4969d3de"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.3.0+0/rustfft.v0.3.0.x86_64-w64-mingw32-julia_version+1.6.3.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "a7c98a95813db03948b7b201a5de5491cbb892ba"
julia_version = "1.7.0"
os = "windows"

    [[rustfft.download]]
    sha256 = "260398bc4a674ec5a610794e7716df9e5159a4a5584fea17a3c8f5ab3c436713"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.3.0+0/rustfft.v0.3.0.x86_64-w64-mingw32-julia_version+1.7.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "8869d5077710d8bcba34a559b34e558d429e5820"
julia_version = "1.8.0"
os = "windows"

    [[rustfft.download]]
    sha256 = "9e6e78451195dd50d574ad89fae83929708257508192067dbc029ae44d611dad"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.3.0+0/rustfft.v0.3.0.x86_64-w64-mingw32-julia_version+1.8.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "6e6ed2756f328ac4379b644854700a8ecc3a4b05"
julia_version = "1.9.0"
os = "windows"

    [[rustfft.download]]
    sha256 = "206fe5ea7cb22b307d59cae18428d121a4c8c8d1411b5b898c1e6f7160b47be6"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.3.0+0/rustfft.v0.3.0.x86_64-w64-mingw32-julia_version+1.9.0.tar.gz"
