[[rustfft]]
arch = "aarch64"
git-tree-sha1 = "abc65fee962752a7b3654faddc09e7bcaec676ee"
julia_version = "1.7.0"
os = "macos"

    [[rustfft.download]]
    sha256 = "b6df6e1e8058aaed93f19fb9af6c812a5db75abb80c68bac0e56b0ef3c49601e"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.3+0/rustfft.v0.0.3.aarch64-apple-darwin-julia_version+1.7.0.tar.gz"
[[rustfft]]
arch = "aarch64"
git-tree-sha1 = "b87ce61f095fe9901458691485341c900d8eda55"
julia_version = "1.8.0"
os = "macos"

    [[rustfft.download]]
    sha256 = "fe58ab3ce0097d49c75ead4421bbecdba8e6a8a855e5f29bca71c49b0eab125b"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.3+0/rustfft.v0.0.3.aarch64-apple-darwin-julia_version+1.8.0.tar.gz"
[[rustfft]]
arch = "aarch64"
git-tree-sha1 = "cf71c1ab69b736bbc0b3974119fb932f0554258f"
julia_version = "1.9.0"
os = "macos"

    [[rustfft.download]]
    sha256 = "818737e56f483ac47cb999c54b5d1d514410c850a1a64a9bcd7b30aa239a162e"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.3+0/rustfft.v0.0.3.aarch64-apple-darwin-julia_version+1.9.0.tar.gz"
[[rustfft]]
arch = "aarch64"
git-tree-sha1 = "0298a1c29fc56cf568e3f2e429b8b8f52dc8bb02"
julia_version = "1.6.3"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "adfcb40fb2d001aaea10aa63eb208cab41f663c2c0cae3543d2c79e59cf5625c"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.3+0/rustfft.v0.0.3.aarch64-linux-gnu-julia_version+1.6.3.tar.gz"
[[rustfft]]
arch = "aarch64"
git-tree-sha1 = "2bb13df4744fe401449c4790566c509f6c89d5b3"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "f6d91e936e77064b296e990bd2e41fa167db6c3ab1edc8962f18e6095e8a64c0"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.3+0/rustfft.v0.0.3.aarch64-linux-gnu-julia_version+1.7.0.tar.gz"
[[rustfft]]
arch = "aarch64"
git-tree-sha1 = "6986a14941a39cb18f84e9451d528d09f90cf3fd"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "dbfc00939bde5c2bcf1874dd57b9c457625192465be0b01587f1faa817e77871"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.3+0/rustfft.v0.0.3.aarch64-linux-gnu-julia_version+1.8.0.tar.gz"
[[rustfft]]
arch = "aarch64"
git-tree-sha1 = "74773c50d3ae99eec40ae5cf032c2c4242000230"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "52db411acc772360e7448d5085bad5d89951afd62b2012c94e761eee10e366fa"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.3+0/rustfft.v0.0.3.aarch64-linux-gnu-julia_version+1.9.0.tar.gz"
[[rustfft]]
arch = "aarch64"
git-tree-sha1 = "b9141532be1c6d51bb9ca9ebaee392aa61df5a78"
julia_version = "1.6.3"
libc = "musl"
os = "linux"

    [[rustfft.download]]
    sha256 = "0faf5290e1c80cf10933babc2314a219967d3d50e366704742c260bbb62bec23"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.3+0/rustfft.v0.0.3.aarch64-linux-musl-julia_version+1.6.3.tar.gz"
[[rustfft]]
arch = "aarch64"
git-tree-sha1 = "2714f0e3925b78f9192f6050349946f6566801cb"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[rustfft.download]]
    sha256 = "3be10a31f300d014399ffebdd28d0133bc84523596a5ea9ff04ff1bef033b748"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.3+0/rustfft.v0.0.3.aarch64-linux-musl-julia_version+1.7.0.tar.gz"
[[rustfft]]
arch = "aarch64"
git-tree-sha1 = "787c5e3df2e5297a7918021d1817039e079e0ce5"
julia_version = "1.8.0"
libc = "musl"
os = "linux"

    [[rustfft.download]]
    sha256 = "49514b707494492b06b986347c2d286b2269f26928f577f7f84d3943dcbe3bad"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.3+0/rustfft.v0.0.3.aarch64-linux-musl-julia_version+1.8.0.tar.gz"
[[rustfft]]
arch = "aarch64"
git-tree-sha1 = "fbffa74cdec606a1ef5ed25bd19109b608eb35e5"
julia_version = "1.9.0"
libc = "musl"
os = "linux"

    [[rustfft.download]]
    sha256 = "b9d5da00079eb844bc68d4b202bf6d76ec9b668a688c3740b2e45538d9416fe7"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.3+0/rustfft.v0.0.3.aarch64-linux-musl-julia_version+1.9.0.tar.gz"
[[rustfft]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4a5e15d0f679a735fbf79689536b0c45914a7aa9"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "cd77290f8669585c409a82417e942aef2f09306bba489844a5da70ba354721a8"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.3+0/rustfft.v0.0.3.armv6l-linux-gnueabihf-julia_version+1.7.0.tar.gz"
[[rustfft]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ced8c2f5c7c776e07c938df82508b4e51eed14da"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "8a35dd41900faaf52c6a67b823ba30499e2bde9c4ecbd20dac413734ddc56255"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.3+0/rustfft.v0.0.3.armv6l-linux-gnueabihf-julia_version+1.8.0.tar.gz"
[[rustfft]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "100271edb3e054f966e83ef18c75af8bebcd50b5"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[rustfft.download]]
    sha256 = "6478d0efcf5a2a21cca409f0b4fc03eea694a66ae5bd6ba55aa9ca31f8e50e7d"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.3+0/rustfft.v0.0.3.armv6l-linux-musleabihf-julia_version+1.7.0.tar.gz"
[[rustfft]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "371c4280a6c2d7c845d60d82b979646066ff15e7"
julia_version = "1.8.0"
libc = "musl"
os = "linux"

    [[rustfft.download]]
    sha256 = "5edc1ffa2c5aa6940156addff0b79430c129fd20e68cccc52e0e0ed7d926f390"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.3+0/rustfft.v0.0.3.armv6l-linux-musleabihf-julia_version+1.8.0.tar.gz"
[[rustfft]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9af9450e43c4f93698ad67ee80f381fd6320eaa8"
julia_version = "1.6.3"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "159561863eec21bf6ce8b0cc3138287a62386e048f760aa60b1a5d638f1f8c12"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.3+0/rustfft.v0.0.3.armv7l-linux-gnueabihf-julia_version+1.6.3.tar.gz"
[[rustfft]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "da7dd8ed813cc4aa3453fb3fc51d5b5d7851d0ef"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "883cd0bc98c5c95808cacd44dd26b6de969d08eaec63e127ec308c1c257b1153"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.3+0/rustfft.v0.0.3.armv7l-linux-gnueabihf-julia_version+1.7.0.tar.gz"
[[rustfft]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cce3c5909a29fe316ad816c0eb7b79c277a9ad54"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "9a5d064d46a0a7412f9c9c3700d1396b873ef8e4909756974d56c223964a577b"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.3+0/rustfft.v0.0.3.armv7l-linux-gnueabihf-julia_version+1.8.0.tar.gz"
[[rustfft]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f52a15260b43b810a59c90482ad7607abc8fb0a5"
julia_version = "1.6.3"
libc = "musl"
os = "linux"

    [[rustfft.download]]
    sha256 = "885fdf420cf95ff1913553a61d1cad3fd34a1dae5590fca2b357258ad64515ce"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.3+0/rustfft.v0.0.3.armv7l-linux-musleabihf-julia_version+1.6.3.tar.gz"
[[rustfft]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "78b5dcb24c052cc5a68e62d332af43e3813a3514"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[rustfft.download]]
    sha256 = "d6afc61d33571c1c869de384ea06a92f21a09ef8810bb8ad65dc5907e631ea37"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.3+0/rustfft.v0.0.3.armv7l-linux-musleabihf-julia_version+1.7.0.tar.gz"
[[rustfft]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4c8cee645f3797fe2491a942156fe939506da471"
julia_version = "1.8.0"
libc = "musl"
os = "linux"

    [[rustfft.download]]
    sha256 = "7c0999bd75ab775a9ff088e229481a8b3e01a4d4ea1adefa0853e16c9ab958c4"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.3+0/rustfft.v0.0.3.armv7l-linux-musleabihf-julia_version+1.8.0.tar.gz"
[[rustfft]]
arch = "i686"
git-tree-sha1 = "3057971c95decc07028c263a75cc6e91a9187bf6"
julia_version = "1.6.3"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "498e04c2b5e7565b2030a065441c02110a21d4b9ee518c79016b731342fa2c20"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.3+0/rustfft.v0.0.3.i686-linux-gnu-julia_version+1.6.3.tar.gz"
[[rustfft]]
arch = "i686"
git-tree-sha1 = "11c329261561ef65e56fe85e5e2f1bf447c1c48e"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "0e5566d7fab1faf4af513cfbe1580b2bd1f1eabde8501d1b2f59265bfa6e78c5"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.3+0/rustfft.v0.0.3.i686-linux-gnu-julia_version+1.7.0.tar.gz"
[[rustfft]]
arch = "i686"
git-tree-sha1 = "9a4a4b4ba4ed20fc9b21d2b2b3500c14731469d8"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "a6c2d405e4ad0edc7fe5b34bfe2b25613be0c857296cdbaadb28eee7b355e077"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.3+0/rustfft.v0.0.3.i686-linux-gnu-julia_version+1.8.0.tar.gz"
[[rustfft]]
arch = "i686"
git-tree-sha1 = "2aa2ed95594b9425dff6f650ed0e5410748ab2cc"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "59c3c328ee1287e25b637cd815b9169a862a0c8d55ce7e786028b0edd68e0da9"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.3+0/rustfft.v0.0.3.i686-linux-gnu-julia_version+1.9.0.tar.gz"
[[rustfft]]
arch = "powerpc64le"
git-tree-sha1 = "e10fcecfa0bc10cd9991926b2a506746fd70ca6f"
julia_version = "1.6.3"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "d93660916d0790bd41f4069c0ddee807e3a351f663c5f89d6a0c7ad5b29733d3"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.3+0/rustfft.v0.0.3.powerpc64le-linux-gnu-julia_version+1.6.3.tar.gz"
[[rustfft]]
arch = "powerpc64le"
git-tree-sha1 = "30c76f105be48c7881cee0cf3f7b25278075b084"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "f3c2fd453a537156ec644609cd9955b8ce4432b17488079056408e2b5f776e56"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.3+0/rustfft.v0.0.3.powerpc64le-linux-gnu-julia_version+1.7.0.tar.gz"
[[rustfft]]
arch = "powerpc64le"
git-tree-sha1 = "53ad487105c4d2916bc93da7aa207ca75f9ee878"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "b2e1205ceaee9c4de4cd6099d1b26a1670902e282ed343b632a63cac4ab0aff5"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.3+0/rustfft.v0.0.3.powerpc64le-linux-gnu-julia_version+1.8.0.tar.gz"
[[rustfft]]
arch = "powerpc64le"
git-tree-sha1 = "41e2c75dcd2a3df3592e38defcce9e11c2dacbd3"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "4a93fe8d3f1c9510298ecf7356fa27fc3a42d59bdcd417304b285deb66f9d8a1"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.3+0/rustfft.v0.0.3.powerpc64le-linux-gnu-julia_version+1.9.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "3eb87b594064e94378a982678b668b56ef94f3a8"
julia_version = "1.6.3"
os = "macos"

    [[rustfft.download]]
    sha256 = "23cc0ac75c20c2ef37e0ff7ad15246c24ca8e5ef87efe55dee4199efcbea37c5"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.3+0/rustfft.v0.0.3.x86_64-apple-darwin-julia_version+1.6.3.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "94f97e6348e8cbf41f0272e45cb5e1451a240a7e"
julia_version = "1.7.0"
os = "macos"

    [[rustfft.download]]
    sha256 = "60a5b4b790302339630c679415460dff7ca70313b4d7c1e3555e207c5b1850b3"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.3+0/rustfft.v0.0.3.x86_64-apple-darwin-julia_version+1.7.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "593147fb24ee0546186f38a727345163164778ba"
julia_version = "1.8.0"
os = "macos"

    [[rustfft.download]]
    sha256 = "ccd82a1e98655e64990294b1af48863e5882470ab4736572d44e0b5f9045504c"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.3+0/rustfft.v0.0.3.x86_64-apple-darwin-julia_version+1.8.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "f0f4cda248aceb231fe90ab5ea69d255c4a8a687"
julia_version = "1.9.0"
os = "macos"

    [[rustfft.download]]
    sha256 = "9221eb06f4237567721a20d18f2c4a8de2792e203cbccc31a652b312ff8b03d7"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.3+0/rustfft.v0.0.3.x86_64-apple-darwin-julia_version+1.9.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "94fb67ff7cc973fec62d52c14cd228b751ea697f"
julia_version = "1.6.3"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "0e65c0cca547d625ba678f2e459265e059bf19a86fa5671d4d7f911abc9fe851"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.3+0/rustfft.v0.0.3.x86_64-linux-gnu-julia_version+1.6.3.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "dcc7b35b6277adfd5cf9f1e26276b2de70ffeb12"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "b4f3e0ad0a16ea510cd90062ef2018af6d3c3c8ef86d020498614c1603aa9153"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.3+0/rustfft.v0.0.3.x86_64-linux-gnu-julia_version+1.7.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "70604ea9fea2e152747fa24f7049803ce4d969f8"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "40bafbd448a099ab5781f0615e81db3417248aae00ce5d60ae081b70301e61ad"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.3+0/rustfft.v0.0.3.x86_64-linux-gnu-julia_version+1.8.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "cd1a9eea046c9ec8acde0be886e6f89685cd54b8"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "19fe95e18da1b35e8c1838d060956b4527ac9ecfcf34d7aa91bd9f6d58c3406d"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.3+0/rustfft.v0.0.3.x86_64-linux-gnu-julia_version+1.9.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "84f08f2998c40f57e0d7578c60404ba9a6386662"
julia_version = "1.6.3"
libc = "musl"
os = "linux"

    [[rustfft.download]]
    sha256 = "bd5b51869949235d1230fcc7a71d07b2bb89bc38b3c21324b66ce9d47469bfbd"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.3+0/rustfft.v0.0.3.x86_64-linux-musl-julia_version+1.6.3.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "18fda4f13ce8c5b444d04414fd7d121529bc042d"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[rustfft.download]]
    sha256 = "44050be90425cebe307e174bc50984808a1805cbefbfebb256d53016d1c4ef63"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.3+0/rustfft.v0.0.3.x86_64-linux-musl-julia_version+1.7.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "4caa4d46bf3dce0a89c127713566d15d5d6d9579"
julia_version = "1.8.0"
libc = "musl"
os = "linux"

    [[rustfft.download]]
    sha256 = "ce1cb8338134cf2a9816542843419550f8c08f660d75873b008ec31e6e615a39"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.3+0/rustfft.v0.0.3.x86_64-linux-musl-julia_version+1.8.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "c705bfa3058aaf8e7d59f258c1933aba3c1a519b"
julia_version = "1.9.0"
libc = "musl"
os = "linux"

    [[rustfft.download]]
    sha256 = "f8ee875d22c7e5dcf17419b3b0d978752188a2d46306c76507b5c5e4af2e7364"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.3+0/rustfft.v0.0.3.x86_64-linux-musl-julia_version+1.9.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "8f5240b116d9776440c2e5cce5c14130a106746b"
julia_version = "1.6.3"
os = "freebsd"

    [[rustfft.download]]
    sha256 = "9a01ca78f2ad22f8acb5c911b96ece4f18bafa7a9d907effd11dae3222de09cf"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.3+0/rustfft.v0.0.3.x86_64-unknown-freebsd-julia_version+1.6.3.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "152df063706c1abda51e13178eb5cf65fb8cea39"
julia_version = "1.7.0"
os = "freebsd"

    [[rustfft.download]]
    sha256 = "f4d2eee0851bd9deb2398f09192a14cd939ab4bc744038e6ab7b3faf72f72480"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.3+0/rustfft.v0.0.3.x86_64-unknown-freebsd-julia_version+1.7.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "2f678bfd5eab3283c7620c53686c3b5db3df9c56"
julia_version = "1.8.0"
os = "freebsd"

    [[rustfft.download]]
    sha256 = "e1271acadad065a406405f3dbcbd8c6ed5c1a36b3c950c0cd3119ec72720df75"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.3+0/rustfft.v0.0.3.x86_64-unknown-freebsd-julia_version+1.8.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "ce8744e5e6d9c586557a30c620e00d9888a616bd"
julia_version = "1.9.0"
os = "freebsd"

    [[rustfft.download]]
    sha256 = "d7f9c79d612bcdb2b13091d7a6e9900ceceac1df26a91d7ae92381b076c5a6e6"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.3+0/rustfft.v0.0.3.x86_64-unknown-freebsd-julia_version+1.9.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "13934839517b2a624e9d30ff1165f5edd6289811"
julia_version = "1.6.3"
os = "windows"

    [[rustfft.download]]
    sha256 = "d6d88ba1ccb150a8384c082ddddad7965d9a18fcb41fc86726ae76b13631d083"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.3+0/rustfft.v0.0.3.x86_64-w64-mingw32-julia_version+1.6.3.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "2b8137e6f7155093485f400cdfe96e7db34302ad"
julia_version = "1.7.0"
os = "windows"

    [[rustfft.download]]
    sha256 = "dea3dd3e1577c987838ccc1934de6e77651b21305ef7948f86ad3851a44e4e8c"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.3+0/rustfft.v0.0.3.x86_64-w64-mingw32-julia_version+1.7.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "f7818183009a2218960a441bac81b46903a88451"
julia_version = "1.8.0"
os = "windows"

    [[rustfft.download]]
    sha256 = "a7f77e88b62663e247e2b16b5bb4aa565177c8ed046ce6a58be4b2a543e6cefe"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.3+0/rustfft.v0.0.3.x86_64-w64-mingw32-julia_version+1.8.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "5feffa48bafbdbfe60350f67eda2dc60cbf3a157"
julia_version = "1.9.0"
os = "windows"

    [[rustfft.download]]
    sha256 = "f0d5816b2bedb95a0f9050be379a7d2f983e19dab9c49cb141adebb0cc8336b7"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.3+0/rustfft.v0.0.3.x86_64-w64-mingw32-julia_version+1.9.0.tar.gz"
