[[rustfft]]
arch = "aarch64"
git-tree-sha1 = "4d59f9e9c4d8fdc14b6a6e3264133a0f297af39a"
julia_version = "1.7.0"
os = "macos"

    [[rustfft.download]]
    sha256 = "25c36c6cd3df21abdc116b16847fae51c4af5bd3325da331162f4de1f83452f9"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.1+0/rustfft.v0.0.1.aarch64-apple-darwin-julia_version+1.7.0.tar.gz"
[[rustfft]]
arch = "aarch64"
git-tree-sha1 = "ba83b4da22e1bb268291640d56ea5b28d373486d"
julia_version = "1.8.0"
os = "macos"

    [[rustfft.download]]
    sha256 = "3c818f7165e11d7ec3aa4f1e98d480524b689d091a506d4f7aa59a87450a1346"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.1+0/rustfft.v0.0.1.aarch64-apple-darwin-julia_version+1.8.0.tar.gz"
[[rustfft]]
arch = "aarch64"
git-tree-sha1 = "8a238343eda467489e2694cdd3afafa26502c3f0"
julia_version = "1.9.0"
os = "macos"

    [[rustfft.download]]
    sha256 = "4109c113c9ae6b139f2ef4a4a659c27289270cccc857cc12b0e81b486e0d18af"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.1+0/rustfft.v0.0.1.aarch64-apple-darwin-julia_version+1.9.0.tar.gz"
[[rustfft]]
arch = "aarch64"
git-tree-sha1 = "050059c7dbef55e23a0c688803465763a5374c8c"
julia_version = "1.6.3"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "b3088b1e2669238fc057f6e2234ec7fa1dcd4cb7b67a54263629fa77267ddd3f"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.1+0/rustfft.v0.0.1.aarch64-linux-gnu-julia_version+1.6.3.tar.gz"
[[rustfft]]
arch = "aarch64"
git-tree-sha1 = "5f8960d52fadc73a380521b63ca1a904a05efca6"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "05e5d70259773a351a648b9a93e5325bc8ff49e88288ec9e04a966cf1e553087"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.1+0/rustfft.v0.0.1.aarch64-linux-gnu-julia_version+1.7.0.tar.gz"
[[rustfft]]
arch = "aarch64"
git-tree-sha1 = "2b3c1552b9722cdcfc85151c6ecd4d7f5c974442"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "62b620b670ad2ea0c0938f9fda40557df6fa978b734740e8b67e792edbf64695"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.1+0/rustfft.v0.0.1.aarch64-linux-gnu-julia_version+1.8.0.tar.gz"
[[rustfft]]
arch = "aarch64"
git-tree-sha1 = "c5133b87288ba4925de1852d0e0d05665f4a5771"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "9d02e7fe8e1d679eecef760598c02479c047b202c8336c20a6978ca0fa98537c"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.1+0/rustfft.v0.0.1.aarch64-linux-gnu-julia_version+1.9.0.tar.gz"
[[rustfft]]
arch = "aarch64"
git-tree-sha1 = "1f7cf1debfda06cdb4b104377f3829575a8fff60"
julia_version = "1.6.3"
libc = "musl"
os = "linux"

    [[rustfft.download]]
    sha256 = "dd5f366c973a84c0f671a6a6d5dbb0c43027bf410f6e55a7fd376c97814c3dc7"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.1+0/rustfft.v0.0.1.aarch64-linux-musl-julia_version+1.6.3.tar.gz"
[[rustfft]]
arch = "aarch64"
git-tree-sha1 = "bb6b9c5539311018c61862d63596d650abba4610"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[rustfft.download]]
    sha256 = "2a72ab8b7ea4537cb554837b3b40b324b69ffa8c33b0ad1f553da449b0aa6dc8"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.1+0/rustfft.v0.0.1.aarch64-linux-musl-julia_version+1.7.0.tar.gz"
[[rustfft]]
arch = "aarch64"
git-tree-sha1 = "431d3dd6b2c687ab7ba74b3dbed01ec884bab335"
julia_version = "1.8.0"
libc = "musl"
os = "linux"

    [[rustfft.download]]
    sha256 = "495773649fd11d64f75027991518046cfd35a0fba8c23b02ad4c7e7f0f600c73"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.1+0/rustfft.v0.0.1.aarch64-linux-musl-julia_version+1.8.0.tar.gz"
[[rustfft]]
arch = "aarch64"
git-tree-sha1 = "e98810cfc2079e6f2c47684d12ac5f8ce8338efb"
julia_version = "1.9.0"
libc = "musl"
os = "linux"

    [[rustfft.download]]
    sha256 = "d6c8a3d349d4733259ce7103d56bf0cb8213db7e0dc1b8c2ade11a7d5e579ec0"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.1+0/rustfft.v0.0.1.aarch64-linux-musl-julia_version+1.9.0.tar.gz"
[[rustfft]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e8e15d2692cbc8231ced625ea004e4f0d059dfd2"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "0ff1493ae79b5122d192a52ef516d5a8aefd7fb392a4752c6a8460d1700f1790"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.1+0/rustfft.v0.0.1.armv6l-linux-gnueabihf-julia_version+1.7.0.tar.gz"
[[rustfft]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8b465c5d3517c560c2968e9b01deb024bd1f35c5"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "1eaec660c84e03c154c1ec897c309517b9165028308d4fb80c456ea7af630bb5"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.1+0/rustfft.v0.0.1.armv6l-linux-gnueabihf-julia_version+1.8.0.tar.gz"
[[rustfft]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d03359d7cdd4fafb65d31595cb3d920c897ef1fb"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[rustfft.download]]
    sha256 = "808045d04ae3dae626f0240380781b9e09139c3763d972a3e0aa46c7fcf0615d"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.1+0/rustfft.v0.0.1.armv6l-linux-musleabihf-julia_version+1.7.0.tar.gz"
[[rustfft]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8afc39d60f919b9034adbbdcd3001f236cc71c27"
julia_version = "1.8.0"
libc = "musl"
os = "linux"

    [[rustfft.download]]
    sha256 = "2171fc0102296ba4a362a9cbbcef872c9d5f571840c8b7d54da4c590928410c0"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.1+0/rustfft.v0.0.1.armv6l-linux-musleabihf-julia_version+1.8.0.tar.gz"
[[rustfft]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c567bce47c9f5a1cf467a5e5eb68cc980fb3c8df"
julia_version = "1.6.3"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "00baf1ef63a554a4d813bf6c617cdd8f5fe9fb03f546caef4da5e70d24b7ce6e"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.1+0/rustfft.v0.0.1.armv7l-linux-gnueabihf-julia_version+1.6.3.tar.gz"
[[rustfft]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "162af9842e482a432b18e8c7775ade4baa0a3450"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "27b29c834c8a36651416b37456dae7607b4638cafd0d52238f3e73c92d2adafe"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.1+0/rustfft.v0.0.1.armv7l-linux-gnueabihf-julia_version+1.7.0.tar.gz"
[[rustfft]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "52c8d4ef03b329c0af4dafd498f5cf02e1eac1ff"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "a8f1c480d86f8c2d512077e4f5dc42e5fd47c5d93392165fdf34f94e6b6eea1a"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.1+0/rustfft.v0.0.1.armv7l-linux-gnueabihf-julia_version+1.8.0.tar.gz"
[[rustfft]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "278da05d6edf1ce36da6ee60ee36f82aaadde25c"
julia_version = "1.6.3"
libc = "musl"
os = "linux"

    [[rustfft.download]]
    sha256 = "42bacfb43e92edec54fbb230a8c98c8fdcc68cee98f526b3e46dbe0b2791a8b2"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.1+0/rustfft.v0.0.1.armv7l-linux-musleabihf-julia_version+1.6.3.tar.gz"
[[rustfft]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0166cef5ff26376febde912ccdebf8a53a983a68"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[rustfft.download]]
    sha256 = "08147a0043061c8a64e6fe603e71ce228520ce1cb7edd350a2c2c2f4608251ab"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.1+0/rustfft.v0.0.1.armv7l-linux-musleabihf-julia_version+1.7.0.tar.gz"
[[rustfft]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "bb24f660d48190b09047ba62faa6e04d93b7dbd1"
julia_version = "1.8.0"
libc = "musl"
os = "linux"

    [[rustfft.download]]
    sha256 = "b9fdc67233d79e72e70cfc6e457c51dadfa910bb4255347d013d7b598caaa828"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.1+0/rustfft.v0.0.1.armv7l-linux-musleabihf-julia_version+1.8.0.tar.gz"
[[rustfft]]
arch = "i686"
git-tree-sha1 = "fc329ae32de974b0312e37f4cc01cf0a871f5b5b"
julia_version = "1.6.3"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "411e8e24c8b1ef0f571b743e761a8e97fb81d33abc778aa786ccd06617f1086d"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.1+0/rustfft.v0.0.1.i686-linux-gnu-julia_version+1.6.3.tar.gz"
[[rustfft]]
arch = "i686"
git-tree-sha1 = "581067c5b95e81afd8946b08c0e7e7fab2a60c4e"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "ff51a7ebbf6b89be5c20a589bf3ee22087e7f5a518a42a1649d79594b30c4369"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.1+0/rustfft.v0.0.1.i686-linux-gnu-julia_version+1.7.0.tar.gz"
[[rustfft]]
arch = "i686"
git-tree-sha1 = "9a00d14c46009350ee6ef65207231fd360d753bd"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "c522712a3f564ac772de006e93207d2e984ad588ce278ff2990e2872ab50c1c9"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.1+0/rustfft.v0.0.1.i686-linux-gnu-julia_version+1.8.0.tar.gz"
[[rustfft]]
arch = "i686"
git-tree-sha1 = "2077eb95bd5fc65c6589bcbbd40ecee8fccce979"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "9d6b737689ec4912eed48665f482ff1fc7a0eee8924f1cb1b5b64dcc4c6fbfd2"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.1+0/rustfft.v0.0.1.i686-linux-gnu-julia_version+1.9.0.tar.gz"
[[rustfft]]
arch = "powerpc64le"
git-tree-sha1 = "57f9b94e6222766d85fb0a5044615c6f3151716b"
julia_version = "1.6.3"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "bbe271e55cebede575ba0e626389672101ae4ab90e0aa3ab8222a410b7a9f25e"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.1+0/rustfft.v0.0.1.powerpc64le-linux-gnu-julia_version+1.6.3.tar.gz"
[[rustfft]]
arch = "powerpc64le"
git-tree-sha1 = "b6faa9c64e06146c9c5014d162ea94c17b067499"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "9efafa343b2656cddb53e97e96a8ed1dd483f56ec6ea0e744853ef8069a9c07d"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.1+0/rustfft.v0.0.1.powerpc64le-linux-gnu-julia_version+1.7.0.tar.gz"
[[rustfft]]
arch = "powerpc64le"
git-tree-sha1 = "75587b88000c959653f2217fe6d9c04ecf0893f2"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "bb1f3ab70dfe0c0a01dc1dd6f0bdd07678499bc2a82464ac08c785f9450e5421"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.1+0/rustfft.v0.0.1.powerpc64le-linux-gnu-julia_version+1.8.0.tar.gz"
[[rustfft]]
arch = "powerpc64le"
git-tree-sha1 = "8bbe4226fe700f59aeec941fcd257b6fe324ac14"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "46c46336180b657fe0f6259a269a6d4df55c40686fabe1bfa82d799770d73e9f"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.1+0/rustfft.v0.0.1.powerpc64le-linux-gnu-julia_version+1.9.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "aa13c8dbc1c3d667f72c39e80c75144c20a8f140"
julia_version = "1.6.3"
os = "macos"

    [[rustfft.download]]
    sha256 = "f6da8c674e95fcf5b445d58552d9679da4912fcfde2c6de81321fdd37c24f8d6"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.1+0/rustfft.v0.0.1.x86_64-apple-darwin-julia_version+1.6.3.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "2d6dcc9edfd62c12e5eb939a7b6582c9fb1ceb31"
julia_version = "1.7.0"
os = "macos"

    [[rustfft.download]]
    sha256 = "c088f830d6c286c9a88e7dfd2e2f50d1430d4ae709a49b7a61bd90d9d4a634ce"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.1+0/rustfft.v0.0.1.x86_64-apple-darwin-julia_version+1.7.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "3f94501f77efdeba30a0637a3144807ebd0b40f2"
julia_version = "1.8.0"
os = "macos"

    [[rustfft.download]]
    sha256 = "96546dbf35ea3a76aee4e46f17d7926e7e2040886a8e720f42b4224511ffbc8f"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.1+0/rustfft.v0.0.1.x86_64-apple-darwin-julia_version+1.8.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "b62e6c6088094595e948a7acaece3e583a5decb4"
julia_version = "1.9.0"
os = "macos"

    [[rustfft.download]]
    sha256 = "30b6cc72852dfa8bd89374121c8563db8795faa15a0fb48327d7522e0ba0b4b0"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.1+0/rustfft.v0.0.1.x86_64-apple-darwin-julia_version+1.9.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "2984b55fb20d0ef023d3a3c070c6e612a841c460"
julia_version = "1.6.3"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "249ec4e11a79c5b9114ef4400ba6aff24cfa494ec11b6185f373549a996e6a43"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.1+0/rustfft.v0.0.1.x86_64-linux-gnu-julia_version+1.6.3.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "893dde3f703dee303117ee285e833bba8d9a8e15"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "8909954327200b8466bacaa9798436d0ff7518a52eff4399fea948d53b2d4b42"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.1+0/rustfft.v0.0.1.x86_64-linux-gnu-julia_version+1.7.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "d9df9d53d935a20cd3939c59f21bc3e7bf4be657"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "ff2c4ca6c82c0d5073f10f48f453a924da6d2151ccb5f7731123323a7e184ff9"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.1+0/rustfft.v0.0.1.x86_64-linux-gnu-julia_version+1.8.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "0d6eec66f5093a433ba20d73e2367c3915f862c4"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "3942cd0a9e327b378271472001eeb139c23c752540995c9862d79816bf02f35a"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.1+0/rustfft.v0.0.1.x86_64-linux-gnu-julia_version+1.9.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "8428f05676f15c70c348ae43ebade0eb5b818fab"
julia_version = "1.6.3"
libc = "musl"
os = "linux"

    [[rustfft.download]]
    sha256 = "196d090d2da3f3c0e26537b2f3788d162b4afe01336b8abfdf1099623d51d865"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.1+0/rustfft.v0.0.1.x86_64-linux-musl-julia_version+1.6.3.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "21f4edabda83da803d7bf7f71f2efb03226daeac"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[rustfft.download]]
    sha256 = "95ef88424c3cb8c81637a76b14329ce0310d97b0da94d85b686ded8a6693878c"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.1+0/rustfft.v0.0.1.x86_64-linux-musl-julia_version+1.7.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "d7ebd95d5bf5854bde14fe6b15710042440858ba"
julia_version = "1.8.0"
libc = "musl"
os = "linux"

    [[rustfft.download]]
    sha256 = "a2d1b284c3aa01d801cd1f8544e9561c5fb9d9ac9bde99699f354bc0e0c786b9"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.1+0/rustfft.v0.0.1.x86_64-linux-musl-julia_version+1.8.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "08802f47d200011b3541e431575a420e71b35f7f"
julia_version = "1.9.0"
libc = "musl"
os = "linux"

    [[rustfft.download]]
    sha256 = "5696e80569709320ff837c5b5be1d5510a32502f074142119d6190eb0af05cd6"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.1+0/rustfft.v0.0.1.x86_64-linux-musl-julia_version+1.9.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "5ae4c66e12004b0bbac9cc164f8c444abe250590"
julia_version = "1.6.3"
os = "freebsd"

    [[rustfft.download]]
    sha256 = "b9b187084243974471556b6c60c8cb68176576c3beecde187cf77e174bb569e5"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.1+0/rustfft.v0.0.1.x86_64-unknown-freebsd-julia_version+1.6.3.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "d3154d08febe20e36e5aa8accf2c64eff4fdfd3f"
julia_version = "1.7.0"
os = "freebsd"

    [[rustfft.download]]
    sha256 = "f8667bf3a08b32c3d878c076c110520c97c5052e2ec82b628a06f1f05153b0a8"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.1+0/rustfft.v0.0.1.x86_64-unknown-freebsd-julia_version+1.7.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "b0f7f6e16b840d68fe9330c8cbe02af9323f5b0d"
julia_version = "1.8.0"
os = "freebsd"

    [[rustfft.download]]
    sha256 = "b9c2455c13a41a983fbfab1dc9b9998f67bb69bbe5b87262b1b727c42f4eb892"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.1+0/rustfft.v0.0.1.x86_64-unknown-freebsd-julia_version+1.8.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "e9f3376b19736ae42ef7f20d604279490f8ded2a"
julia_version = "1.9.0"
os = "freebsd"

    [[rustfft.download]]
    sha256 = "890d6b2e4199100b79b52af245180d2967967db451bb7704776601b00b8c7dea"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.1+0/rustfft.v0.0.1.x86_64-unknown-freebsd-julia_version+1.9.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "2df57219a547af4ff2ab8ffe243efdde63303507"
julia_version = "1.6.3"
os = "windows"

    [[rustfft.download]]
    sha256 = "be744b32a6dff43397e35ee18d495fc33544ffb7533238c1c0b00f4415396e3e"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.1+0/rustfft.v0.0.1.x86_64-w64-mingw32-julia_version+1.6.3.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "98afc8a8ad48f3e7ed5aad421ff670e35d6dfafd"
julia_version = "1.7.0"
os = "windows"

    [[rustfft.download]]
    sha256 = "1b0a2c92d8b8f0598ed74f7c0287ad82841934db37dcbb971153bf5a6a16c123"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.1+0/rustfft.v0.0.1.x86_64-w64-mingw32-julia_version+1.7.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "38d6f69ff187d05025dd01492f10c04ce98964d4"
julia_version = "1.8.0"
os = "windows"

    [[rustfft.download]]
    sha256 = "01f47d87da21f7bb295d3089a254cb7e9ba416d9d399a30cb4a4997d7762525a"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.1+0/rustfft.v0.0.1.x86_64-w64-mingw32-julia_version+1.8.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "4aa07d60ba3b1c04982961efc0e25feea15c2e70"
julia_version = "1.9.0"
os = "windows"

    [[rustfft.download]]
    sha256 = "0bdee7875e45dbdf4a23c2ef4cc6143cb4849046aecb7ce8fc59d8975d9c88fc"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.0.1+0/rustfft.v0.0.1.x86_64-w64-mingw32-julia_version+1.9.0.tar.gz"
