[[rustfft]]
arch = "aarch64"
git-tree-sha1 = "ff47d8c84b67bcab8723405cce313df1747fb93c"
julia_version = "1.10.0"
os = "macos"

    [[rustfft.download]]
    sha256 = "403a91bb1d39f98cbb314b0c7a3c52de0d1a53f94b26691bc5aa41df25f9fd10"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.5.0+0/rustfft.v0.5.0.aarch64-apple-darwin-julia_version+1.10.0.tar.gz"
[[rustfft]]
arch = "aarch64"
git-tree-sha1 = "e89ff1b7fe600a872b6ac9e253da9eee060fbf28"
julia_version = "1.11.0"
os = "macos"

    [[rustfft.download]]
    sha256 = "69c1e5f9b6f7782fbb44e586070460fc4b29688316862e2686e73752a57bd1e3"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.5.0+0/rustfft.v0.5.0.aarch64-apple-darwin-julia_version+1.11.0.tar.gz"
[[rustfft]]
arch = "aarch64"
git-tree-sha1 = "53cbdb1f69975ee0bc6333e266e4fae83b74f474"
julia_version = "1.12.0"
os = "macos"

    [[rustfft.download]]
    sha256 = "951145ecaf9f0222630ecc5e4f3dad79518a6a21fd66cc69d30cb4646999c0b6"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.5.0+0/rustfft.v0.5.0.aarch64-apple-darwin-julia_version+1.12.0.tar.gz"
[[rustfft]]
arch = "aarch64"
git-tree-sha1 = "9df4957c5a3972b075ed44079b8538a33c07c471"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "b57ba6674d7b8f264c0cb2685463f301f3fb23f01c094aa73626725a4beb07d7"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.5.0+0/rustfft.v0.5.0.aarch64-linux-gnu-julia_version+1.10.0.tar.gz"
[[rustfft]]
arch = "aarch64"
git-tree-sha1 = "70d5e17131804840f6dc0163ba04e3d8fb1aa553"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "c325ae56830178b691cd25f8626a3a8d9294d7147c4bc2161dfdfc500c7d69bf"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.5.0+0/rustfft.v0.5.0.aarch64-linux-gnu-julia_version+1.11.0.tar.gz"
[[rustfft]]
arch = "aarch64"
git-tree-sha1 = "eda725ff8417c17bd31a50eef913952868b0a72e"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "783d662cec819281c8662ee2528477736356955b00cd14b3169a3b879d4e0f95"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.5.0+0/rustfft.v0.5.0.aarch64-linux-gnu-julia_version+1.12.0.tar.gz"
[[rustfft]]
arch = "aarch64"
git-tree-sha1 = "e3f2db6081d2d793080a28b39437a1aa4e7ae94e"
julia_version = "1.10.0"
libc = "musl"
os = "linux"

    [[rustfft.download]]
    sha256 = "423ac3a7aaa2c16169ae93b2a82bab407f2c6654cc98ffae8ecb8ef98da06ec0"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.5.0+0/rustfft.v0.5.0.aarch64-linux-musl-julia_version+1.10.0.tar.gz"
[[rustfft]]
arch = "aarch64"
git-tree-sha1 = "a35d34bd31eae17bcd3e2c02a5fa19f307ffee87"
julia_version = "1.11.0"
libc = "musl"
os = "linux"

    [[rustfft.download]]
    sha256 = "fa20fe1c5cac3662b9fe04832f1a6c42a4b3fcb9ca3479ebe9fd9b0a07d6524e"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.5.0+0/rustfft.v0.5.0.aarch64-linux-musl-julia_version+1.11.0.tar.gz"
[[rustfft]]
arch = "aarch64"
git-tree-sha1 = "45ead40465894e2e273365ff0b1ed62bef2d557e"
julia_version = "1.12.0"
libc = "musl"
os = "linux"

    [[rustfft.download]]
    sha256 = "c1b2ed3e5c84d151e907c57981a9632aafa5536ad9a3056772c4ad68d9a1da7d"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.5.0+0/rustfft.v0.5.0.aarch64-linux-musl-julia_version+1.12.0.tar.gz"
[[rustfft]]
arch = "i686"
git-tree-sha1 = "fba1583f033da9e7d3efb65d12813cd6f2eba3a3"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "755446d497c640337e672c40da7642d8c17534324a70c47dad27a6e39c25b8e4"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.5.0+0/rustfft.v0.5.0.i686-linux-gnu-julia_version+1.10.0.tar.gz"
[[rustfft]]
arch = "i686"
git-tree-sha1 = "21c8fd66b1987518db949c8318c29d66064b0f4f"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "916f98322e9c931db0a2b8c960bfd67507e9289cf4eb5e5ddb463c16e22946b0"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.5.0+0/rustfft.v0.5.0.i686-linux-gnu-julia_version+1.11.0.tar.gz"
[[rustfft]]
arch = "i686"
git-tree-sha1 = "d56a5aacdc33bc56f4d1a3070a76318f2af21135"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "c9971d255a4293c29b7fb789cd0acc296fcfcbb27d6bda87b83f6d18a2bd4db8"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.5.0+0/rustfft.v0.5.0.i686-linux-gnu-julia_version+1.12.0.tar.gz"
[[rustfft]]
arch = "powerpc64le"
git-tree-sha1 = "581b94644123fe0224775d00f09d2cd41b4f5390"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "6a14388b8d00365db34561586aa4268d6bcbddc43267ab26c1e65fb340aeaf00"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.5.0+0/rustfft.v0.5.0.powerpc64le-linux-gnu-julia_version+1.10.0.tar.gz"
[[rustfft]]
arch = "powerpc64le"
git-tree-sha1 = "7688dd599b41b82838e34db7ae181509775d522e"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "b8de2f94af67c7b262302df633584ea71b770f2132ceca664f38665b10124c64"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.5.0+0/rustfft.v0.5.0.powerpc64le-linux-gnu-julia_version+1.11.0.tar.gz"
[[rustfft]]
arch = "powerpc64le"
git-tree-sha1 = "135c57484dcfe810814c1ba7664ae93977ed1386"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "3a1921764631eb46aca12621f8056f1e3a66e47e237efcb4d4fe1dd77d610259"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.5.0+0/rustfft.v0.5.0.powerpc64le-linux-gnu-julia_version+1.12.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "ddbceba767217a6384ea501cb119be11f2cd55b4"
julia_version = "1.10.0"
os = "macos"

    [[rustfft.download]]
    sha256 = "3fac50fe51ca53852bb780cd53ec763e1222063a8bc1079feab7f667433fc3d6"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.5.0+0/rustfft.v0.5.0.x86_64-apple-darwin-julia_version+1.10.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "b531f63d82b7931921239131599a6203494b0468"
julia_version = "1.11.0"
os = "macos"

    [[rustfft.download]]
    sha256 = "18f96a886685ef3b6aaa49f688aebca461e5ff4dba52246e3a3a9319b2d03a06"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.5.0+0/rustfft.v0.5.0.x86_64-apple-darwin-julia_version+1.11.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "04e534b502001c36551d6c94df8544947048a7e2"
julia_version = "1.12.0"
os = "macos"

    [[rustfft.download]]
    sha256 = "d8d9014a3e01e78f8492bb455b2f4822d62d944124f588991ace25a836476eaa"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.5.0+0/rustfft.v0.5.0.x86_64-apple-darwin-julia_version+1.12.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "d6f86fa3a091c4d0618b59520ddd6da1763d0764"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "9d0762724703f513162ce4908dbd740423399f01e09d5a3749fcc3e04bb3dfb0"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.5.0+0/rustfft.v0.5.0.x86_64-linux-gnu-julia_version+1.10.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "7627ee4675b0dc390b5fea4d000ecddc93ae494f"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "83a279e026bca8e8080dbcb97d7f74231c14e5f8ca2b6db3911806ef54a4991d"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.5.0+0/rustfft.v0.5.0.x86_64-linux-gnu-julia_version+1.11.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "3a2fbc934d55f0742415a1f8b5fe7355221b88f9"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "1c5f5e75c57be6d381ffd7a4583a202d1aeb1ea27d9b01e3788990b7a8837e66"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.5.0+0/rustfft.v0.5.0.x86_64-linux-gnu-julia_version+1.12.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "34f26dfae0ffe0987c07d9f4e53d0e855d5a6ccc"
julia_version = "1.10.0"
libc = "musl"
os = "linux"

    [[rustfft.download]]
    sha256 = "3976b8189bafd19789c16641b58daef5d56ebd65bc24a5fdd54c789fae939971"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.5.0+0/rustfft.v0.5.0.x86_64-linux-musl-julia_version+1.10.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "07522e4cca4a8dfe76a69fcea28ef2e8d6a8867c"
julia_version = "1.11.0"
libc = "musl"
os = "linux"

    [[rustfft.download]]
    sha256 = "da03dbb96440671bf0c418dfc5543d7da888ea11f5758aa2c91cfb42d867a852"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.5.0+0/rustfft.v0.5.0.x86_64-linux-musl-julia_version+1.11.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "58ee8c61960023162136d1e4522107d5e685d301"
julia_version = "1.12.0"
libc = "musl"
os = "linux"

    [[rustfft.download]]
    sha256 = "11f056d90a50e88133efcce51687b27d6cac6c046a989d2e33f91a579c97dec2"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.5.0+0/rustfft.v0.5.0.x86_64-linux-musl-julia_version+1.12.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "17da885407b8b269384461d50b4aa01b0ef6af9c"
julia_version = "1.10.0"
os = "freebsd"

    [[rustfft.download]]
    sha256 = "7eb9a37eb8fa83df5ae1cfcbf09755d412ffc87f72cfaadaecb1d56e2f39d347"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.5.0+0/rustfft.v0.5.0.x86_64-unknown-freebsd-julia_version+1.10.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "a85bacbc7f064d9567470684147a4fa315a9c879"
julia_version = "1.11.0"
os = "freebsd"

    [[rustfft.download]]
    sha256 = "70cb480b360aa28e44e44e16bed3f505ec4b88cc823b1735bdbb6bf3fc67e702"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.5.0+0/rustfft.v0.5.0.x86_64-unknown-freebsd-julia_version+1.11.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "3a2be5edc4202c4d534c15aa949fcc4121b29114"
julia_version = "1.12.0"
os = "freebsd"

    [[rustfft.download]]
    sha256 = "ede4e3b73a21c5df7eeffd4494c2517be340e6d6a6eb3d8f28a04d7b091b01a3"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.5.0+0/rustfft.v0.5.0.x86_64-unknown-freebsd-julia_version+1.12.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "11f8a82c0236c1584f139deec7feb5bb071808d3"
julia_version = "1.10.0"
os = "windows"

    [[rustfft.download]]
    sha256 = "afd52f523b8b829cc95c2045b9c1742fc13e1759dd6bf567d85b496e846106be"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.5.0+0/rustfft.v0.5.0.x86_64-w64-mingw32-julia_version+1.10.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "86805f2df6ae0c5ee17782425c8f9941047d40ba"
julia_version = "1.11.0"
os = "windows"

    [[rustfft.download]]
    sha256 = "73908453c02d54d3ae891e3286f2bfdd6dca274f0b2f63324427861d6e2b57e5"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.5.0+0/rustfft.v0.5.0.x86_64-w64-mingw32-julia_version+1.11.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "9d7d12be638c125e21e4348dfb33380b2b949e6f"
julia_version = "1.12.0"
os = "windows"

    [[rustfft.download]]
    sha256 = "e8667bbc40d6e5994cc0850ae88afc52ecf1a9df30ccd844513dc1e0924f44da"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.5.0+0/rustfft.v0.5.0.x86_64-w64-mingw32-julia_version+1.12.0.tar.gz"
