[[rustfft]]
arch = "aarch64"
git-tree-sha1 = "5b9507ecc457ac59e87078349166c0212c894c94"
julia_version = "1.7.0"
os = "macos"

    [[rustfft.download]]
    sha256 = "cba997e50e943b087eef3079f57a2ab2c2c71dfcf68d11402ed63df28794ea39"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.1.1+0/rustfft.v0.1.1.aarch64-apple-darwin-julia_version+1.7.0.tar.gz"
[[rustfft]]
arch = "aarch64"
git-tree-sha1 = "57e279b07500a10a5dc7cd3b7fccae9b75205a34"
julia_version = "1.8.0"
os = "macos"

    [[rustfft.download]]
    sha256 = "4345635eb4d852f2aaa490487b2afdfd05425f5cac98188b52a5a2b26a70621c"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.1.1+0/rustfft.v0.1.1.aarch64-apple-darwin-julia_version+1.8.0.tar.gz"
[[rustfft]]
arch = "aarch64"
git-tree-sha1 = "0320e7eb14bfca13e4be9510b2fa61665dfe8633"
julia_version = "1.9.0"
os = "macos"

    [[rustfft.download]]
    sha256 = "e3d5dbcfc56ab2f45ce3fe81dcaf5f060267a4dbc5a1d35c843488f7529c6a78"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.1.1+0/rustfft.v0.1.1.aarch64-apple-darwin-julia_version+1.9.0.tar.gz"
[[rustfft]]
arch = "aarch64"
git-tree-sha1 = "98c5b99dbef31ad2ec48dbe2d0e36a43cdde90a5"
julia_version = "1.6.3"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "9e092281859cc773a9287a49ec67b79f3ab60733fe45410e86d09f777f5713b1"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.1.1+0/rustfft.v0.1.1.aarch64-linux-gnu-julia_version+1.6.3.tar.gz"
[[rustfft]]
arch = "aarch64"
git-tree-sha1 = "ca5c5ee9fd25045b70ee6254d357ebea2812c1d7"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "5c69a9f24f327ec9b8508504fe1345eb642fa654c135a1573f6ac4276e90538f"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.1.1+0/rustfft.v0.1.1.aarch64-linux-gnu-julia_version+1.7.0.tar.gz"
[[rustfft]]
arch = "aarch64"
git-tree-sha1 = "2eb65e0c1d216233189549c5277efad867336f0a"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "78bba25254d4d92d16d65fa903a55c5462a9cb7cba5edf3450be404859c5618f"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.1.1+0/rustfft.v0.1.1.aarch64-linux-gnu-julia_version+1.8.0.tar.gz"
[[rustfft]]
arch = "aarch64"
git-tree-sha1 = "2e00346280245d5473a5a0b3538dc75bab7365a8"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "d372851c25a3432a60d76e1d2b191450599143841481a82a8b2c9e0a0fbed43c"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.1.1+0/rustfft.v0.1.1.aarch64-linux-gnu-julia_version+1.9.0.tar.gz"
[[rustfft]]
arch = "aarch64"
git-tree-sha1 = "d2f373c948d6971ba1503732bc0c61836148a07f"
julia_version = "1.6.3"
libc = "musl"
os = "linux"

    [[rustfft.download]]
    sha256 = "62d501637d34a31518bcdf71eecb1f108ef82ab6cf140ac48730649c3b1ed09e"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.1.1+0/rustfft.v0.1.1.aarch64-linux-musl-julia_version+1.6.3.tar.gz"
[[rustfft]]
arch = "aarch64"
git-tree-sha1 = "66f40031792fa52bf663b4741ad45ec1740cf296"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[rustfft.download]]
    sha256 = "367b4f32ca62de40d01d7634ff9eb437dd91a5c5de2ce36c6bd78b5d810b7a88"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.1.1+0/rustfft.v0.1.1.aarch64-linux-musl-julia_version+1.7.0.tar.gz"
[[rustfft]]
arch = "aarch64"
git-tree-sha1 = "a05ccd682d328d3eb29eb451773d22ff17570038"
julia_version = "1.8.0"
libc = "musl"
os = "linux"

    [[rustfft.download]]
    sha256 = "67b09dfb6c8a56ba4ae91aeb362f7159758d48f90918b2483926e77bf36bb754"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.1.1+0/rustfft.v0.1.1.aarch64-linux-musl-julia_version+1.8.0.tar.gz"
[[rustfft]]
arch = "aarch64"
git-tree-sha1 = "72ba053059b915026fe422d3edd9c28a57dd90c8"
julia_version = "1.9.0"
libc = "musl"
os = "linux"

    [[rustfft.download]]
    sha256 = "17561c404bddfb09d1d8a44654693c07c0747e488a7130297697eb0408eec425"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.1.1+0/rustfft.v0.1.1.aarch64-linux-musl-julia_version+1.9.0.tar.gz"
[[rustfft]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6cf0b722ac7de709e258839a9768408cff931437"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "beb5c5dc8bf6f189338cc820435052f9c3d6ca1976b3ef9844f1fef3327a01c5"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.1.1+0/rustfft.v0.1.1.armv6l-linux-gnueabihf-julia_version+1.7.0.tar.gz"
[[rustfft]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e7eaccf8c6ce077cdd31312f70893ec1810a6957"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "1e7b83218bbfb5d16bf99732d1d21f4b38e496e43138239ed2b83d978107cedf"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.1.1+0/rustfft.v0.1.1.armv6l-linux-gnueabihf-julia_version+1.8.0.tar.gz"
[[rustfft]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "15d42db75b73f429ec1a3a270cb9179be6814f6e"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[rustfft.download]]
    sha256 = "37c014b68371790ff5da48d42701310441e5903b61778ba43bea51fad00aca17"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.1.1+0/rustfft.v0.1.1.armv6l-linux-musleabihf-julia_version+1.7.0.tar.gz"
[[rustfft]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bc7c325d89271b0473a7dae810e54edd54ac0af5"
julia_version = "1.8.0"
libc = "musl"
os = "linux"

    [[rustfft.download]]
    sha256 = "1a0440540dde5bc76ca9db9a04d41bdc3de0b5eab71c517ad4b2e061ee7618cf"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.1.1+0/rustfft.v0.1.1.armv6l-linux-musleabihf-julia_version+1.8.0.tar.gz"
[[rustfft]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c6a6f0d36de1829d25d6b22b54612eb9984f3adf"
julia_version = "1.6.3"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "abd8c6529ceb82aaef8db67f3f5967fae6d6b5244ebfe7add3dae68f5a83d103"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.1.1+0/rustfft.v0.1.1.armv7l-linux-gnueabihf-julia_version+1.6.3.tar.gz"
[[rustfft]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b6f2154309e3823291d748bf69b55c238dd3ba6f"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "e3476d9549f0b9cf0515fdd0ad090c1962820fa410892914cd8eac4c8bfc2d6c"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.1.1+0/rustfft.v0.1.1.armv7l-linux-gnueabihf-julia_version+1.7.0.tar.gz"
[[rustfft]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "609f542e6deaa4438760121b8cbe9c4e1659d82d"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "af5598034d4165d8f211e5f4f05b6ef5db925f2d9641c2dad93dbb44a3ab55cf"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.1.1+0/rustfft.v0.1.1.armv7l-linux-gnueabihf-julia_version+1.8.0.tar.gz"
[[rustfft]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b932b624aaaeedbdc48342bb6e984af039b2cd75"
julia_version = "1.6.3"
libc = "musl"
os = "linux"

    [[rustfft.download]]
    sha256 = "a3b8f42e22e98bf813e49d928f77ff0bfe650ccca979c6b2c393e458aec4ddbc"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.1.1+0/rustfft.v0.1.1.armv7l-linux-musleabihf-julia_version+1.6.3.tar.gz"
[[rustfft]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6935c1bb296a49878fd0250772abaec5f1efb00b"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[rustfft.download]]
    sha256 = "3decc625fa54a4dd8d30db69dfa06ae7a69864a11078740606a4447cf3545a8e"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.1.1+0/rustfft.v0.1.1.armv7l-linux-musleabihf-julia_version+1.7.0.tar.gz"
[[rustfft]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5e8960bbf5b373bb2beb1151462172477fbe0ebf"
julia_version = "1.8.0"
libc = "musl"
os = "linux"

    [[rustfft.download]]
    sha256 = "2f9418cb9698fc9fe4eeff145410818a20a28ba753e0391bc4e593d533e086db"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.1.1+0/rustfft.v0.1.1.armv7l-linux-musleabihf-julia_version+1.8.0.tar.gz"
[[rustfft]]
arch = "i686"
git-tree-sha1 = "bb5fd2d7c8ccad9b2e77260cb3973b0fd160bc9f"
julia_version = "1.6.3"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "391a6ab2435d4dcfa192fd1bda9c684ac2784f837ce816d83154be3f77257018"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.1.1+0/rustfft.v0.1.1.i686-linux-gnu-julia_version+1.6.3.tar.gz"
[[rustfft]]
arch = "i686"
git-tree-sha1 = "a682c9b412739bc657ee388fd0479e090c434598"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "655265bfac2fdf5aeac1145a277ace415d24b4c379875ea2c830b99389d62619"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.1.1+0/rustfft.v0.1.1.i686-linux-gnu-julia_version+1.7.0.tar.gz"
[[rustfft]]
arch = "i686"
git-tree-sha1 = "d8a7e7c46d1e5b15c3449dffa6614acd3726d24a"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "3c692144fb639e693d0cea0e2282d29c3b064c8d6921403b330473c27749365f"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.1.1+0/rustfft.v0.1.1.i686-linux-gnu-julia_version+1.8.0.tar.gz"
[[rustfft]]
arch = "i686"
git-tree-sha1 = "765474e89cfc8053932ca091c280ece359df3062"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "ddaadb985f053e10e77991838244571dccda757c4a328e863cd008297b3a462e"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.1.1+0/rustfft.v0.1.1.i686-linux-gnu-julia_version+1.9.0.tar.gz"
[[rustfft]]
arch = "powerpc64le"
git-tree-sha1 = "6217cce910796a88b42a008c44297346f76d58c8"
julia_version = "1.6.3"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "87d8dbcdb8eb9224695a7df50836a4d413c62a36b6f452c84c7b4767da2db2d4"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.1.1+0/rustfft.v0.1.1.powerpc64le-linux-gnu-julia_version+1.6.3.tar.gz"
[[rustfft]]
arch = "powerpc64le"
git-tree-sha1 = "a8a8dd35aa7fd660dca9f81af947fb8d0994e9bd"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "da455b79d6a12f53aa330195caeee475cc8d9b65e1ea3a1db87445606d3bbe87"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.1.1+0/rustfft.v0.1.1.powerpc64le-linux-gnu-julia_version+1.7.0.tar.gz"
[[rustfft]]
arch = "powerpc64le"
git-tree-sha1 = "e5638dc62c31d7f748010c0efecacb2e703a1255"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "6ba2912ce64980302c9a176a54b1a5125607a761c28a454238888e1bd1d83ba1"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.1.1+0/rustfft.v0.1.1.powerpc64le-linux-gnu-julia_version+1.8.0.tar.gz"
[[rustfft]]
arch = "powerpc64le"
git-tree-sha1 = "e0f0e333b3714114dbe54caffa278bf5f0e8da46"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "dc9e9bd18d04f3c3d0224b849e732fcafbd7b1390b93350f687e467c4288783c"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.1.1+0/rustfft.v0.1.1.powerpc64le-linux-gnu-julia_version+1.9.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "84b250be9ee6e8b96df733859647e1d0bbdbe4ae"
julia_version = "1.6.3"
os = "macos"

    [[rustfft.download]]
    sha256 = "af37fbd5f62052501858401b25b2d98430b04d4393edf408c4bb9d85f09312d6"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.1.1+0/rustfft.v0.1.1.x86_64-apple-darwin-julia_version+1.6.3.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "e5bbf0e0a8e96c20318c1113b6e3d874bffa9aaa"
julia_version = "1.7.0"
os = "macos"

    [[rustfft.download]]
    sha256 = "7f1c52ad5a85cfa4a0c73cc2248895d8e2ea01507650d65d0bb882d51ab62445"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.1.1+0/rustfft.v0.1.1.x86_64-apple-darwin-julia_version+1.7.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "e1afc38b24fab7dff7cb7397b10deddbbeb09ae8"
julia_version = "1.8.0"
os = "macos"

    [[rustfft.download]]
    sha256 = "7ce0f2e22ee554109b5f2b67146e8c5a8f6b3dfe843c9e6eff8e747ea3e7fe6d"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.1.1+0/rustfft.v0.1.1.x86_64-apple-darwin-julia_version+1.8.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "20c15195abfb37586b74705b05957ad51d0afb12"
julia_version = "1.9.0"
os = "macos"

    [[rustfft.download]]
    sha256 = "592a2db122c0ee9fd548fe94fdc6b8366a6050eb1155c41c596a7dbcbe33fe5a"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.1.1+0/rustfft.v0.1.1.x86_64-apple-darwin-julia_version+1.9.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "cebf7f41ee072d59ae51e100e84e47db356a4df2"
julia_version = "1.6.3"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "406e613388e3593731513366d5d9c4a212230ab21561005386034283256eda7b"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.1.1+0/rustfft.v0.1.1.x86_64-linux-gnu-julia_version+1.6.3.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "bcc1eff0489dedc04c80c295f7d5e848876209cb"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "a26cb37b97c61d646cd55b7a835222a0b87a48f2656a2b9c50d2dda3199697bf"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.1.1+0/rustfft.v0.1.1.x86_64-linux-gnu-julia_version+1.7.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "73814d9cbed7ddf65c079a51ab580ad04f3310bf"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "77a37d3903603862e1db79b1998638faa243fc0c09fb0607df3a5482d41f17f9"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.1.1+0/rustfft.v0.1.1.x86_64-linux-gnu-julia_version+1.8.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "a698876cc29391f318cd3de3d60adb2ee19d493c"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[rustfft.download]]
    sha256 = "f0059027a0dba0f92fb221d2b7c94a171e0f118b8bb2394fd34c8e99cab80095"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.1.1+0/rustfft.v0.1.1.x86_64-linux-gnu-julia_version+1.9.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "38ac98315bbd3fe761383d0c36d878b1b75c9039"
julia_version = "1.6.3"
libc = "musl"
os = "linux"

    [[rustfft.download]]
    sha256 = "9de24c3e453a4db30b5d008b676e9a6f05e490cc2492c33744c314a5bfe50068"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.1.1+0/rustfft.v0.1.1.x86_64-linux-musl-julia_version+1.6.3.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "a4db729851ecfebc37fab8d85fbd961d651e65d6"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[rustfft.download]]
    sha256 = "464ad584b2e37987c49f2a5de708931432c84406af8a412e3927c370b9e9663d"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.1.1+0/rustfft.v0.1.1.x86_64-linux-musl-julia_version+1.7.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "e06118c77634f61681812abe33057f92de5124e3"
julia_version = "1.8.0"
libc = "musl"
os = "linux"

    [[rustfft.download]]
    sha256 = "9954838ca0007134c0422b9d056ba36f02e930721b5b77bc7d2f7c551402b0a3"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.1.1+0/rustfft.v0.1.1.x86_64-linux-musl-julia_version+1.8.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "409deb7e365ca79e68944569abb1d2c36fce7810"
julia_version = "1.9.0"
libc = "musl"
os = "linux"

    [[rustfft.download]]
    sha256 = "1a5fccc59f4d1f8be53c70e09f740e0b107812232ab9e57dfaec3c57566de7d8"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.1.1+0/rustfft.v0.1.1.x86_64-linux-musl-julia_version+1.9.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "8973e1819024f7d813536aa40609f5b5f77880a3"
julia_version = "1.6.3"
os = "freebsd"

    [[rustfft.download]]
    sha256 = "aa5cd72c6b3700edda5ec8a6ebbe1a607ed5c1d33fa1144e3d251552dc1723a1"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.1.1+0/rustfft.v0.1.1.x86_64-unknown-freebsd-julia_version+1.6.3.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "35cb0f9acdf01050bfd4fe0219b68bfac8370ee3"
julia_version = "1.7.0"
os = "freebsd"

    [[rustfft.download]]
    sha256 = "6163292924b8cbf65d3b23ff5046064d370729f8b2bb0f8b4e0e10512b3a212e"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.1.1+0/rustfft.v0.1.1.x86_64-unknown-freebsd-julia_version+1.7.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "81bbe7af1482d45194cc375e0dc757bbec4e8ecd"
julia_version = "1.8.0"
os = "freebsd"

    [[rustfft.download]]
    sha256 = "ff6b3afac8083442c04e4aa7f99fd54f93671ab20379a6142dcf700947122166"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.1.1+0/rustfft.v0.1.1.x86_64-unknown-freebsd-julia_version+1.8.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "d1a685e602b0d2fd6376d0e8ef33e62bfd43aa79"
julia_version = "1.9.0"
os = "freebsd"

    [[rustfft.download]]
    sha256 = "24950df725abad02f907e13a9596909291708c9c010c5e872dd35bd1aa5b51c5"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.1.1+0/rustfft.v0.1.1.x86_64-unknown-freebsd-julia_version+1.9.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "da756536213c77e7308f28c945dfce9b6b20a8dd"
julia_version = "1.6.3"
os = "windows"

    [[rustfft.download]]
    sha256 = "3b5d7b92a478c9dfa5ccd68e4f51b95c2b025515adaf94cbeeef800f1a9ac4ae"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.1.1+0/rustfft.v0.1.1.x86_64-w64-mingw32-julia_version+1.6.3.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "0d94cce7354c53293c511105f5f8169629d52bec"
julia_version = "1.7.0"
os = "windows"

    [[rustfft.download]]
    sha256 = "8314bc0f4de3265c124e922895377bb18370d5dcaf31fe245799f321a9623f2c"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.1.1+0/rustfft.v0.1.1.x86_64-w64-mingw32-julia_version+1.7.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "9a2606814f72b2b2be47f85e7747b11a7cf4d97a"
julia_version = "1.8.0"
os = "windows"

    [[rustfft.download]]
    sha256 = "ed61d3abc965965a196b15b706a63dc9b8014cf7bc345ba58d263cfad5970746"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.1.1+0/rustfft.v0.1.1.x86_64-w64-mingw32-julia_version+1.8.0.tar.gz"
[[rustfft]]
arch = "x86_64"
git-tree-sha1 = "676714ecae80e77f9d348bffd406e5a237045509"
julia_version = "1.9.0"
os = "windows"

    [[rustfft.download]]
    sha256 = "c5ccd951852b2b6cc03c13e7444f143eb74c8fc2996a5ed6a402ca405a7c596c"
    url = "https://github.com/JuliaBinaryWrappers/rustfft_jll.jl/releases/download/rustfft-v0.1.1+0/rustfft.v0.1.1.x86_64-w64-mingw32-julia_version+1.9.0.tar.gz"
